apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudethix-nginx-haneef
  namespace: cloudethix-haneef
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cloudethix-nginx-haneef
        image: skhaneef19/cloudethix-nginix-haneef:v1
        ports:
        - containerPort: 80
